tasks:

  - init: |

      docker compose build

  - command: |

      docker compose up

ports:

  - port: 5000
    onOpen: open-browser
  - port: 8443
    onOpen: open-browser
  - port: 8800
    onOpen: open-preview
  - port: 8983
    onOpen: open-preview     